# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6f58d0c6702c5f58d389eec0b5b78837f1485ae627ed8eac4c11097105cccd3ec02219b18ae23ac7e26ced93278f0943d86f263f3483beb25fdc0e09a14b422

test:
  secret_key_base: a3cba163aea76e748cd1c54e3cc1181312de672b132459c8353fb4088a670ad938389291aaf6d1a9693474bf872b680a49f2eb5bcbfbd8c7af4a281a19001ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
